#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>

#include "libft.h"

int main(void)
{
	char a = '0', b = 'a', c = 'Z', d = '@';
	char str[] = "copy this message";
	char str2[] = "copy this message";
	char zero[] = "this is for bzero";
	char mmset[] = "this is for memset";
	char mmcpy[] = "this is for memcpy";
	char mmove[] = "this is for memmove";
	char mmcpy2[] = "Learningisfun";
	char mmove2[] = "Learningisfun";
	char *ptr1, *ptr2, *ptr11, *ptr22;

	ptr1 = str;
	ptr2 = str2;
	ptr11 = mmcpy2;
	ptr22 = mmove2;
	printf("--------------------------\n");
	printf("1) ft_isalpha\n");
	printf("%-10s || %c || %s\n","MINE",  a, ft_isalpha(a) != 0 ? "ALPHA" : "NOT ALPHA");
	printf("%-10s || %c || %s\n","BUILT",  a, isalpha(a) != 0 ? "ALPHA" : "NOT ALPHA");
	printf("%-10s || %c || %s\n","MINE",  b, ft_isalpha(b) != 0 ? "ALPHA" : "NOT ALPHA");
	printf("%-10s || %c || %s\n","BUILT",  b, isalpha(b) != 0 ? "ALPHA" : "NOT ALPHA");
	printf("%-10s || %c || %s\n","MINE",  c, ft_isalpha(c) != 0 ? "ALPHA" : "NOT ALPHA");
	printf("%-10s || %c || %s\n","BUILT",  c, isalpha(c) != 0 ? "ALPHA" : "NOT ALPHA");
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("2) ft_isdigit\n");
	printf("%-10s || %c || %s\n","MINE",  a, ft_isdigit(a) != 0 ? "DIGIT" : "NOT DIGIT");
	printf("%-10s || %c || %s\n","BUILT",  a, isdigit(a) != 0 ? "DIGIT" : "NOT DIGIT");
	printf("%-10s || %c || %s\n","MINE",  b, ft_isdigit(b) != 0 ? "DIGIT" : "NOT DIGIT");
	printf("%-10s || %c || %s\n","BUILT",  b, isdigit(b) != 0 ? "DIGIT" : "NOT DIGIT");
	printf("%-10s || %c || %s\n","MINE",  c, ft_isdigit(c) != 0 ? "DIGIT" : "NOT DIGIT");
	printf("%-10s || %c || %s\n","BUILT",  c, isdigit(c) != 0 ? "DIGIT" : "NOT DIGIT");
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("3) ft_isalnum\n");
	printf("%-10s || %c || %s\n","MINE",  a, ft_isalnum(a) != 0 ? "ALNUM" : "NOT ALNUM");
	printf("%-10s || %c || %s\n","BUILT",  a, isalnum(a) != 0 ? "ALNUM" : "NOT ALNUM");
	printf("%-10s || %c || %s\n","MINE",  b, ft_isalnum(b) != 0 ? "ALNUM" : "NOT ALNUM");
	printf("%-10s || %c || %s\n","BUILT",  b, isalnum(b) != 0 ? "ALNUM" : "NOT ALNUM");
	printf("%-10s || %c || %s\n","MINE",  c, ft_isalnum(c) != 0 ? "ALNUM" : "NOT ALNUM");
	printf("%-10s || %c || %s\n","BUILT",  c, isalnum(c) != 0 ? "ALNUM" : "NOT ALNUM");
	printf("%-10s || %c || %s\n","MINE",  d, ft_isalnum(d) != 0 ? "ALNUM" : "NOT ALNUM");
	printf("%-10s || %c || %s\n","BUILT",  d, isalnum(d) != 0 ? "ALNUM" : "NOT ALNUM");
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("4) ft_isascii\n");
	printf("Char: %c || %d\n", 'C', ft_isascii('C'));
	printf("Char: %c || %d\n", '@', ft_isascii('@'));
	printf("Char: %c || %d\n", 160, ft_isascii(160));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("5) ft_isprint\n");
	printf("Char %c || %d\n", '@', ft_isprint('@'));
	printf("Char %c || %d\n", 'a', ft_isprint('a'));
	printf("Char %c || %d\n", 0, ft_isprint(0));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("6) ft_strlen\n");
	printf("MINE || Str: %s || Length: %lu\n", "COUNT", ft_strlen("COUNT"));
	printf("BUILT || Str: %s || Length: %lu\n", "COUNT", strlen("COUNT"));
	printf("MINE || Str: %s || Length: %lu\n", "", ft_strlen(""));
	printf("BUILT || Str: %s || Length: %lu\n", "", strlen(""));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("7) ft_memset\n");
	printf("Size: %d || Str: %s\n", 3, (char *)ft_memset(mmset, 'a', 3 * sizeof(char)));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("8) ft_bzero\n");
	ft_bzero(zero, 2);
	printf("Str: %s\n", zero);
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("9) ft_memcpy\n");
	printf("Dst: %s || Src: %s || New: %s\n", "this is for memcpy", "sad", (char *)ft_memcpy(mmcpy, "sad", 2 * sizeof(char)));
	printf("Dst: %s || Src: %s || New: %s\n", "py this message", "copy this message", (char *)ft_memcpy(ptr1 + 2, ptr1, 5 * sizeof(char)));
	ft_memcpy(ptr11 + 8, ptr11, 5);
	printf("Dst: %s || Src: %s || New: %s\n", "isfun", "Learningisfun", mmcpy2);
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("10) ft_memmove\n");
	printf("Dst: %s || Src: %s || New: %s\n", "this is for memmove", "sad", (char *)ft_memmove(mmove, "sad", 2 * sizeof(char)));
	printf("Dst: %s || Src: %s || New: %s\n", "py this message", "copy this message", (char *)ft_memmove(ptr2 + 2, ptr2, 5 * sizeof(char)));
	ft_memmove(ptr22 + 8, ptr22, 5);
	printf("Dst: %s || Src: %s || New: %s\n", "isfun", "Learningisfun", mmove2);
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("11) ft_strlcpy\n");
	printf("Dst: %s || Src: %s || New: %zu\n", "cococis message", "sad", ft_strlcpy(ptr1, "sad", 2 * sizeof(char)));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("12) ft_strlcat\n");
	printf("Dst: %s || Src: %s || New: %zu\n", "copy is message", "sad", ft_strlcat(ptr2, "sad", 12 * sizeof(char)));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("13) ft_toupper\n");
	printf("Char %c || New: %c\n", 'a', ft_toupper('a'));
	printf("Char %c || New: %c\n", 'A', ft_toupper('A'));
	printf("Char %c || New: %c\n", 1, ft_toupper(1));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("14) ft_tolower\n");
	printf("Char %c || New: %c\n", 'a', ft_tolower('a'));
	printf("Char %c || New: %c\n", 'A', ft_tolower('A'));
	printf("Char %c || New: %c\n", 2, ft_tolower(2));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("15) ft_strchr\n");
	printf("Str: %s || New: %s\n", "asdsa", ft_strchr("asdsa", 'a'));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("16) ft_strrchr\n");
	printf("Str: %s || New: %s\n", "asdsafidel", ft_strrchr("asdsafidel", 'a'));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("17) ft_strncmp\n");
	printf("Str1: %s || Str2: %s || Result: %d\n", "asdsad", "aaa", ft_strncmp("asdsad", "aaa", 2));
	printf("Str1: %s || Str2: %s || Result: %d\n", "a", "aaa", ft_strncmp("asdsad", "aaa", 2));
	printf("Str1: %s || Str2: %s || Result: %d\n", "Bsdsd", "aaa", ft_strncmp("asdsad", "aaa", 2));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("18) ft_memchr\n");
	printf("Str: %s || Char: %c || New: %s\n", "iamhappy", 'a', (char *)ft_memchr("iamhappy", 'a', 3 * sizeof(char)));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("19) ft_memcmp\n");
	printf("Str1: %s || Str2: %s || New: %d\n", "iamhappy", "iamsad", ft_memcmp("iamhappy", "iamsad", 4 * sizeof(char)));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("20) ft_strnstr\n");
	printf("Haystack: %s || Needle: %s || Len: %d || New: %s\n", "iamhappy", "happy", 8, ft_strnstr("iamhappy", "happy", 8 * sizeof(char)));
	printf("Haystack: %s || Needle: %s || Len: %d || New: %s\n", "iamhappyfidel", "happy", 8, ft_strnstr("iamhappyfidel", "happy", 8 * sizeof(char)));
	printf("Haystack: %s || Needle: %s || Len: %d || New: %s\n", "iamhappy", "hsappy", 8, ft_strnstr("iamhappy", "hsappy", 8 * sizeof(char)));
	printf("Haystack: %s || Needle: %s || Len: %d || New: %s\n", "iamhappy", "happy", 2, ft_strnstr("iamhappy", "happy", 2 * sizeof(char)));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("21) ft_atoi\n");
	printf("Mine || Value: %s || New: %d\n", "-99999999999999999999999999", ft_atoi("-99999999999999999999999999"));
	printf("Mine || Value: %s || New: %d\n", "-99999999999999999999999999", atoi("-99999999999999999999999999"));
	printf("Mine || Value: %s || New: %d\n", "99999999999999999999999999", ft_atoi("99999999999999999999999999"));
	printf("Mine || Value: %s || New: %d\n", "99999999999999999999999999", atoi("99999999999999999999999999"));
	printf("Mine || Value: %s || New: %d\n", " -+214", ft_atoi(" -+214"));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("22) ft_calloc\n");
	printf("Count: %d || Len: %d || New: %s\n", 2, 2, (char *)ft_calloc(2, 2));
	printf("Count: %d || Len: %d || New: %s\n", 0, 0, (char *)ft_calloc(0, 0));
	printf("--------------------------\n");
	printf("--------------------------\n");
	printf("23) ft_strdup\n");
	printf("Str: %s || New: %s\n", "fidel", ft_strdup("fidel"));
	printf("Str: %s || New: %s\n", "", ft_strdup(""));
	printf("--------------------------\n");
	printf("--------------------------\n");
	return (0);
}
